- name: Install Apache
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Ensure Apache is started and enabled
  service:
    name: apache2
    state: started
    enabled: yes

